# Generated by Django 3.2.8 on 2021-10-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
