# Generated by Django 3.2.8 on 2021-11-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstService', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
