# Generated by Django 3.2.8 on 2021-11-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstService', '0008_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='imagesResult/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_result',
        ),
    ]
